### ISSUE TITLE
tons of tracebacks about ExtraParameterProblem

### ISSUE THREAD

**Issue by mozbhearsum** [mozilla-releng/treestatus#5]
Noticed these in GCP:
```
Traceback (most recent call last):
  File "/appenv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/appenv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/appenv/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/appenv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/appenv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/appenv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/appenv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/appenv/lib/python3.7/site-packages/connexion/decorators/decorator.py", line 48, in wrapper
    response = function(request)
  File "/appenv/lib/python3.7/site-packages/connexion/decorators/uri_parsing.py", line 173, in wrapper
    response = function(request)
  File "/appenv/lib/python3.7/site-packages/connexion/decorators/validation.py", line 356, in wrapper
    raise ExtraParameterProblem(formdata_errors, query_errors)
connexion.exceptions.ExtraParameterProblem: (set(), {'all'})
```

Link for those with access: https://console.cloud.google.com/errors/COrPsc3ujdnAjgE?time=P1D&project=moz-fx-relengapi-prod-b398

**Comment by rail** [comment]
Should be fixed by PR #6
